{{- if and .Values.apiToken (not .Values.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "org-cost-api.fullname" . }}-token
  labels:
    {{- include "org-cost-api.labels" . | nindent 4 }}
type: Opaque
stringData:
  ORG_COST_API_TOKEN: {{ .Values.apiToken | quote }}
{{- end }}
