#!/usr/bin/env bash
# Generate a starter config.yaml from an AWS Organizations payer profile.
#
# Usage:
#   ./scripts/bootstrap-config.sh --profile org-payer.AdministratorAccess
#   ./scripts/bootstrap-config.sh --profile org-payer.AdministratorAccess --output config.yaml
#   ./scripts/bootstrap-config.sh --profile org-payer.AdministratorAccess --profile-map profiles.csv
#
# profiles.csv format (header optional):
#   account_id,profile
#   111111111111,Production.AdministratorAccess
#
# Writes a complete config.yaml skeleton with billing_profile and all ACTIVE org accounts.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
PROFILE=""
OUTPUT=""
PREFIX=""
REGION="eu-west-1"
PROFILE_MAP=""

usage() {
  sed -n '2,12p' "$0" | sed 's/^# \?//'
  exit "${1:-0}"
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --profile|-p)
      PROFILE="${2:?--profile requires a value}"
      shift 2
      ;;
    --output|-o)
      OUTPUT="${2:?--output requires a value}"
      shift 2
      ;;
    --prefix)
      PREFIX="${2:?--prefix requires a value}"
      shift 2
      ;;
    --region|-r)
      REGION="${2:?--region requires a value}"
      shift 2
      ;;
    --profile-map)
      PROFILE_MAP="${2:?--profile-map requires a path}"
      shift 2
      ;;
    -h|--help)
      usage 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage 1
      ;;
  esac
done

if [[ -z "$PROFILE" ]]; then
  echo "ERROR: --profile is required" >&2
  usage 1
fi

if [[ -z "$OUTPUT" ]]; then
  OUTPUT="$ROOT/config.yaml"
fi

if [[ -e "$OUTPUT" ]]; then
  echo "ERROR: $OUTPUT already exists — use a different --output or remove the file" >&2
  exit 1
fi

LIST_SCRIPT="$ROOT/scripts/list-org-accounts.sh"
chmod +x "$LIST_SCRIPT"

ACCOUNTS_YAML="$("$LIST_SCRIPT" --profile "$PROFILE" --prefix "$PREFIX" --region "$REGION")"

if [[ -n "$PROFILE_MAP" ]]; then
  if [[ ! -f "$PROFILE_MAP" ]]; then
    echo "ERROR: profile map not found: $PROFILE_MAP" >&2
    exit 1
  fi
  ACCOUNTS_YAML="$(PROFILE_MAP="$PROFILE_MAP" python3 -c '
import csv, os, re, sys

text = sys.stdin.read()
path = os.environ["PROFILE_MAP"]
by_id = {}
with open(path, newline="") as f:
    for row in csv.reader(f):
        if not row or row[0].strip().lower() == "account_id":
            continue
        by_id[row[0].strip()] = row[1].strip()

lines = text.splitlines()
out = []
i = 0
while i < len(lines):
    line = lines[i]
    m = re.match(r"\s+id:\s*\"(\d{12})\"", line)
    if m and m.group(1) in by_id:
        out.append(line)
        i += 1
        while i < len(lines) and not lines[i].strip().startswith("profile:"):
            out.append(lines[i])
            i += 1
        if i < len(lines) and lines[i].strip().startswith("profile:"):
            out.append(f"    profile: {by_id[m.group(1)]}")
            i += 1
        continue
    out.append(line)
    i += 1
print("\n".join(out))
' <<< "$ACCOUNTS_YAML")"
fi

{
  echo "# Generated by scripts/bootstrap-config.sh — review before use"
  echo "# Docs: docs/getting-started.md · docs/iam-minimal-setup.md"
  echo ""
  echo "listen_addr: \":8080\""
  echo "# Docker prod UI is served on :8080; use http://localhost:5173 for Vite dev"
  echo "cors_origin: \"http://localhost:8080\""
  echo "cost_lookback_days: 30"
  echo ""
  echo "# Org payer Cost Explorer profile (management account)"
  echo "billing_profile: $PROFILE"
  echo ""
  echo "# Optional API auth — uncomment for production"
  echo "# api_token_env: ORG_COST_API_TOKEN"
  echo ""
  echo "accounts:"
  echo "$ACCOUNTS_YAML"
} > "$OUTPUT"

ACCT_COUNT="$(grep -c '^  - name:' "$OUTPUT" || true)"
echo "Wrote $OUTPUT (${ACCT_COUNT} accounts)" >&2
echo "" >&2
echo "Next steps:" >&2
echo "  1. Edit profile names in $OUTPUT if they don't match ~/.aws/config" >&2
echo "  2. Add billing_profile: account on member-billed rows — docs/member-billed-account.md" >&2
echo "  3. ./scripts/verify-aws-auth.sh $OUTPUT --format markdown" >&2
echo "  4. aws sso login   # if using SSO profiles" >&2
echo "  5. docker compose -f docker-compose.prod.yml up --build" >&2
echo "     # optional chat: docker compose -f docker-compose.full.yml up --build" >&2
